An exception on <%= @bug.environment.project.name %> has reopened this bug,
which was previously marked as fixed and deployed:

<%= project_environment_bug_url @bug.environment.project, @bug.environment, @bug %>

Project:       <%= @bug.environment.project.name %>
Environment:   <%= @bug.environment.name %>
Revision:      <%= @bug.revision %>
Fix Commit:    <%= @bug.resolution_revision %>

<%= @bug.class_name %>
<% if @bug.special_file? %>
in <%= @bug.file %>
<% else %>
in <%= @bug.file %>:<%= @bug.line %>
<% end %>

You should revisit the bug and make sure that it was actually fixed. If an
additional fix is required, update the fix commit under the Management page.

        Yours truly,
        Squash
